### ISSUE TITLE
CSRF issue

### ISSUE THREAD

**Issue by Xitro01** [mpast/mobileAudit#61]
After cloning the repo (also tried the latest release) and building/running the docker, the application seems to work fine.
Yet, when I create a project and try to upload a file (POST), I get a CSRF issue: "CSRF verification failed. request aborted".

Any idea how this can be solved?

**Comment by mpast** [comment]
Hi @Xitro01,
Since creating the repo and uploading the apk has passed some time? I only can think that maybe that was the issue because the CSRF token was not valid once you did the second request,
Could you try to refresh the page and do it again?
If that does not work and I can't reproduce the issue, could you give me more info about the docker version and host that is running the app?
Thanks!

**Comment by Xitro01** [comment]
Still the same issues. I'm running it on:
Linux kali 5.16.0-kali1-amd64 #1 SMP PREEMPT Debian 5.16.7-2kali1 (2022-02-10) x86_64 GNU/Linux
Docker version 20.10.11+dfsg1, build dea9396

**Comment by mpast** [comment]
Hi @Xitro01 
We have been unable to reproduce, can you share some steps or screenshots? including the network tab to see the issue? Thanks

**Comment by Xitro01** [comment]
I currently don't have the time to look into this issue further. Whenever I have another mobile application audit, I will try to use mobileAudit. Hopefully the issue has solved itself by then, otherwise I will re-open another issue. Therefore I will close this issue for now.
